const Employee = [
    {
        profileid: '2750',
        deptname: 'Tổ Trợ lý',
        shortname: 'ASSISTANT',
        email: 'trung.le@gosu.vn',
        fullname: 'Lê Quang Trung',
        jodid: 'Giám đốc',
        jodname: 'DIRECTOR ASSISTANT',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/2750/0986c839b733455a97a812f357a4fcc6.jpg',
        dept: 'to tro ly'
    },
    {
        profileid: '92',
        deptname: 'Tổ trợ lý',
        shortname: 'ASSISTANT',
        email: 'vinh.le@gosu.vn',
        fullname: 'Lê Quang Vinh',
        jodid: 'Nhân sự',
        jodname: 'ASSISTANT',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/92/9fa66733b11b40e7ac7054326ccc8554.jpg',
        dept: 'to tro ly'
    },
    {
        profileid: '1318',
        deptname: 'Tổ Trợ lý',
        shortname: 'ASSISTANT',
        email: 'yen.ha@gosu.vn',
        fullname: 'Hà Võ Phương Yến',
        jodid: 'Nhân sự',
        jodname: 'ASSISTANT',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1318/db6fa08523b64d2e9c5f4f4d058c05a0.jpg',
        dept: 'to tro ly'
    },
    {
        profileid: '1470',
        deptname: 'Tổ Trợ lý',
        shortname: 'ASSISTANT',
        email: 'phucuong.tran@gosu.vn',
        fullname: 'Trần Phú Cường',
        jodid: 'Nhân sự',
        jodname: 'INTERNAL PR',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1470/e2a18e61daf74527a32d05302db6e0fb.jpg',
        dept: 'to tro ly'
    },
    {
        profileid: '1547',
        deptname: 'Tổ Trợ lý',
        shortname: 'ASSISTANT',
        email: 'phat.lam@gosu.vn',
        fullname: 'Lâm Huỳnh Phát',
        jodid: 'Nhân sự',
        jodname: 'ASSISTANT HCM',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1547/30917968c5f549f28d584bdc3250fee8.jpg',
        dept: 'to tro ly'
    },
    {
        profileid: '1619',
        deptname: 'Tổ Trợ lý',
        shortname: 'ASSISTANT',
        email: 'thien.vu@gosu.vn',
        fullname: 'Vũ Thanh Thiên',
        jodid: 'Nhân sự',
        jodname: 'ASSISTANT',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1619/a248adc5c1514f7e9080f00f4c7468bd.jpg',
        dept: 'to tro ly'
    },
    {
        profileid: '1628',
        deptname: 'Tổ Trợ lý',
        shortname: 'ASSISTANT',
        email: 'can.nguyen@gosu.vn',
        fullname: 'Nguyễn Cần',
        jodid: 'Nhân sự',
        jodname: 'ASSISTANT HCM',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1628/c40016aa2832469f85c916bd1c8ea596.jpg',
        dept: 'to tro ly'
    },
    {
        profileid: '1656',
        deptname: 'Tổ Trợ lý',
        shortname: 'ASSISTANT',
        email: 'hien.le@gosu.vn',
        fullname: 'Lê Thúy Hiền',
        jodid: 'Nhân sự',
        jodname: 'ASSISTANT',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1656/8974b35d33164b2aaa0a94488af65ce0.jpg',
        dept: 'to tro ly'
    },
    {
        profileid: '2749',
        deptname: 'Tổ Trợ lý',
        shortname: 'ASSISTANT',
        email: 'chuong.doan@gosu.vn',
        fullname: 'Đoàn Minh Chương',
        jodid: 'Nhân sự',
        jodname: 'ASSISTANT HCM',
        area: 'SGN',
        avatar: '/static/uploads/sinhnhat/default_avatar.svg',
        dept: 'to tro ly'
    },
    {
        profileid: '3802',
        deptname: 'Hành chính Nhân sự',
        shortname: 'HR & ADMIN ',
        email: 'trinh.hoang@gosu.vn',
        fullname: 'Hoàng Thị Mai Trinh',
        jodid: 'Nhân sự',
        jodname: 'ASSISTANT',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/3802/067e7bd8ddd0444394b42ce352341b51.jpg',
        dept: 'to tro ly'
    },
    {
        profileid: '252',
        email: 'tien.kieu@gosu.vn',
        fullname: 'Kiều Bảo Tiên',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/252/dc5c1cb107ae4444bc085628083da577.jpg',
        dept: 'Nemo',
        jodid: 'Giám đốc'
    },
    {
        profileid: '110',
        email: 'son.le@gosu.vn',
        fullname: 'Lê Minh Sơn',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/110/304ef4942f4a454da1b69641f80ee461.jpg',
        dept: 'Nemo',
        jodid: 'Phó giám đốc'
    },
    {
        profileid: '1679',
        email: 'duc01.nguyen@gosu.vn',
        fullname: 'Nguyễn Đức',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1679/af890c514b4247e69838205533420d1a.jpg',
        dept: 'Nemo',
        jodid: 'Nhân sự'
    },
    {
        profileid: '1724',
        email: 'phe.tran@gosu.vn',
        fullname: 'Trần Duy Phê',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1724/68f6fa9e35ca4ea79375c4bfad19d364.jpg',
        dept: 'Nemo',
        jodid: 'Nhân sự'
    },
    {
        profileid: '1725',
        email: 'huuhoang.tran@gosu.vn',
        fullname: 'Trần Hữu Hoàng',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1725/c94a0f4a51bb4f1b9e1ee42ffe4fd47d.jpg',
        dept: 'Nemo',
        jodid: 'Nhân sự'
    },
    {
        profileid: '3788',
        email: 'uyen.truong@gosu.vn',
        fullname: 'Trương Tất Uyển',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/3788/463472dc67864abc9115692ecb1a684f.jpg',
        dept: 'Nemo',
        jodid: 'Nhân sự'
    },
    {
        profileid: '160',
        deptname: 'Kỹ thuật Hạ tầng',
        shortname: 'TECHNOLOGY CENTER',
        email: 'tai.dao@gosu.vn',
        fullname: 'Đào Trương Duy Tài',
        jodid: 'Trưởng bộ phận',
        jodname: 'TECHNICAL INF MANAGER - HCM',
        area: 'SGN',
        avatar: '/static/uploads/sinhnhat/default_avatar.svg',
        dept: 'ky thuat ha tang'
    },
    {
        profileid: '121',
        deptname: 'Kỹ thuật Hạ tầng',
        shortname: 'HARDWARE',
        email: 'thien.phung@gosu.vn',
        fullname: 'Phùng Hữu Thiện',
        jodid: 'Nhân sự',
        jodname: 'TECHNICAL INF - HUE',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/121/2056767ac2f54a558f89fc52656d1f71.jpg',
        dept: 'ky thuat ha tang'
    },
    {
        profileid: '122',
        deptname: 'Kỹ thuật Hạ tầng',
        shortname: 'HARDWARE',
        email: 'phuoc.ha@gosu.vn',
        fullname: 'Hà Hữu Phước',
        jodid: 'Nhân sự',
        jodname: 'TECHNICAL INF - HUE',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/122/c1314df84069468191bc879caa1c2b24.jpg',
        dept: 'ky thuat ha tang'
    },
    {
        profileid: '1672',
        deptname: 'Kỹ thuật Hạ tầng',
        shortname: 'TECHNOLOGY CENTER',
        email: 'long.nguyen@gosu.vn',
        fullname: 'Nguyễn Đình Long',
        jodid: 'Nhân sự',
        jodname: 'TECHNICAL INF - HCM',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1672/b1f28a3080724c9a8bc51aff1e698052.jpg',
        dept: 'ky thuat ha tang'
    },
    {
        profileid: '1623',
        email: 'hiep.pham@gosu.vn',
        fullname: 'Phạm Văn Hiệp',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1623/6b37674627b641fe9055c8591d5d714b.jpg',
        dept: 'tai chinh ke toan',
        jodid: 'Giám đốc'
    },
    {
        profileid: '34',
        email: 'nhu.ton@gosu.vn',
        fullname: 'Tôn Nữ Thảo Quỳnh Như',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/34/6b37674627b641fe9055c8591d5d714b.jpg',
        dept: 'tai chinh ke toan',
        jodid: 'Trưởng nhóm'
    },
    {
        profileid: '38',
        email: 'thuy.le@gosu.vn',
        fullname: 'Lê Thị Bích Thủy',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/38/290aafd95c544ccc9e07703dd68ea490.jpg',
        dept: 'tai chinh ke toan',
        jodid: 'Nhân sự'
    },
    {
        profileid: '147',
        email: 'ly.vo@gosu.vn',
        fullname: 'Võ Thị Bích Ly',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/147/8cf60f9c457944b9a80720638656fb62.jpg',
        dept: 'tai chinh ke toan',
        jodid: 'Nhân sự'
    },
    {
        profileid: '273',
        email: 'mai.tran@gosu.vn',
        fullname: 'Trần Thị Ngọc Mai',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/273/73d7c07a0dbb42c2bfd7cded2d2f936c.jpg',
        dept: 'tai chinh ke toan',
        jodid: 'Nhân sự'
    },
    {
        profileid: '1351',
        email: 'quynh.ho@gosu.vn',
        fullname: 'Hồ Như Quỳnh',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1351/249e3f27f98d459c9be46ffcf1df2f5f.jpg',
        dept: 'tai chinh ke toan',
        jodid: 'Nhân sự'
    },
    {
        profileid: '1634',
        email: 'huong.tran@gosu.vn',
        fullname: 'Trần Thị Hương',
        avatar: '/static/uploads/sinhnhat/default_avatar.svg',
        dept: 'tai chinh ke toan',
        jodid: 'Nhân sự'
    },
    {
        profileid: '271',
        deptname: 'Trung tâm Quan Hệ Quốc Tế',
        shortname: 'IRC CENTER',
        email: 'phuong.thach@gosu.vn',
        fullname: 'Thạch Phương',
        jodid: 'Giám Đốc',
        jodname: 'CAMBODIAN MANAGER',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/271/a174bfd6bd4e477d814625f63f9613d0.jpg',
        dept: 'irc'
    },
    {
        profileid: '1601',
        deptname: 'Trung tâm Quan Hệ Quốc Tế',
        shortname: 'IRC CENTER',
        email: 'phuong.tran@gosu.vn',
        fullname: 'Trần Lệ Phương',
        jodid: 'Giám Đốc',
        jodname: 'CHINESE MANAGER',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1601/712b7d2663b14dd6b4da968ba09712a7.jpg',
        dept: 'irc'
    },
    {
        profileid: '25',
        deptname: 'Trung tâm Quan Hệ Quốc Tế',
        shortname: 'IRC CENTER',
        email: 'thuong.nguyen@gosu.vn',
        fullname: 'Nguyễn Phước Diệu Thường',
        jodid: 'Phó Giám Đốc',
        jodname: 'IRC DEPUTY DIRECTOR',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/25/8c406f01a9754588a62f2c6a56439c63.jpg',
        dept: 'irc'
    },
    {
        profileid: '145',
        deptname: 'Trung tâm Quan Hệ Quốc Tế',
        shortname: 'IRC CENTER',
        email: 'kien.huynh@gosu.vn',
        fullname: 'Huỳnh Thái Kiên',
        jodid: 'Phó Giám Đốc',
        jodname: 'IRC VICE DIRECTOR',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/145/abcad161c3a74d0e823d5ace36d2cdd3.jpg',
        dept: 'irc'
    },
    {
        profileid: '20',
        deptname: 'Điều phối',
        shortname: 'Điều phối',
        email: 'huyen.nguyen@gosu.vn',
        fullname: 'Nguyễn Thị Nhật Huyền',
        jodid: 'Phó nhóm',
        jodname: 'OV _MANAGER',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/20/ac37b55215a84540ac8450cb71befdef.jpg',
        dept: 'irc'
    },
    {
        profileid: '14',
        deptname: 'Điều phối',
        shortname: 'Điều phối',
        email: 'anh.nguyen@gosu.vn',
        fullname: 'Nguyễn Thị Vân Anh',
        jodid: 'Nhân sự',
        jodname: 'OVERSEAS',
        area: 'HUI',
        avatar: '/static/uploads/sinhnhat/default_avatar.svg',
        dept: 'irc'
    },
    {
        profileid: '18',
        deptname: 'Điều phối',
        shortname: 'Điều phối',
        email: 'hoanganh.nguyen@gosu.vn',
        fullname: 'Nguyễn Thị Hoàng Anh',
        jodid: 'Nhân sự',
        jodname: 'OVERSEAS',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/18/3eb1c318fb094eaca869b226030ea4b2.jpg',
        dept: 'irc'
    },
    {
        profileid: '19',
        deptname: 'Điều phối',
        shortname: 'Điều phối',
        email: 'hieu.lai@gosu.vn',
        fullname: 'Lại Thị Hiếu',
        jodid: 'Nhân sự',
        jodname: 'OVERSEAS',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/19/f658768284dd4a9188d4079dff84c77b.jpg',
        dept: 'irc'
    },
    {
        profileid: '21',
        deptname: 'Điều phối',
        shortname: 'Điều phối',
        email: 'mai.le@gosu.vn',
        fullname: 'Lê Vũ Hoàng Mai',
        jodid: 'Nhân sự',
        jodname: 'OVERSEAS',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/21/17e98826adaa45948f44e38cafea3d50.jpg',
        dept: 'irc'
    },
    {
        profileid: '22',
        deptname: 'Thương vụ',
        shortname: 'Thương vụ',
        email: 'ngoc.tran@gosu.vn',
        fullname: 'Trần Như Bảo Ngọc',
        jodid: 'Nhân sự',
        jodname: 'IRC HUE',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/22/b4f69472777d40a3be31d144d34f8c20.jpg',
        dept: 'irc'
    },
    {
        profileid: '264',
        deptname: 'Trung tâm Quan Hệ Quốc Tế',
        shortname: 'IRC CENTER',
        email: 'trang.thach@gosu.vn',
        fullname: 'Thạch Thị Trang',
        jodid: 'Nhân sự',
        jodname: 'IRC HCM',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/264/15ecbc681a6b4c30a81a98ee941c34ef.jpg',
        dept: 'irc'
    },
    {
        profileid: '1498',
        deptname: 'Điều phối',
        shortname: 'Điều phối',
        email: 'quynhnhu.nguyen@gosu.vn',
        fullname: 'Nguyễn Khắc Thị Quỳnh Như',
        jodid: 'Nhân sự',
        jodname: 'OVERSEAS',
        area: 'HUI',
        avatar: '/static/uploads/sinhnhat/default_avatar.svg',
        dept: 'irc'
    },
    {
        profileid: '1528',
        deptname: 'Điều phối',
        shortname: 'Điều phối',
        email: 'dan.nguyen@gosu.vn',
        fullname: 'Nguyễn Thị Thanh Đan',
        jodid: 'Nhân sự',
        jodname: 'OVERSEAS',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1528/6646d776b9774f95a1cc66e23fd2eba3.jpg',
        dept: 'irc'
    },
    {
        profileid: '1531',
        deptname: 'Điều phối',
        shortname: 'Điều phối',
        email: 'thaonguyen.nguyen@gosu.vn',
        fullname: 'Nguyễn Thị Thảo Nguyên',
        jodid: 'Nhân sự',
        jodname: 'OVERSEAS',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1531/3f6ad651670640bf8423b885d9191c90.jpg',
        dept: 'irc'
    },
    {
        profileid: '1577',
        deptname: 'Trung tâm Quan Hệ Quốc Tế',
        shortname: 'IRC CENTER',
        email: 'tam.tran@gosu.vn',
        fullname: 'Trần Minh Tâm',
        jodid: 'Nhân sự',
        jodname: 'IRC HCM',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1577/ac60c2aa0a77458299e7b1da46cb6a88.jpg',
        dept: 'irc'
    },
    {
        profileid: '1734',
        deptname: 'Điều phối',
        shortname: 'Điều phối',
        email: 'minhnhat.nguyen@gosu.vn',
        fullname: 'Nguyễn Đức Minh Nhật',
        jodid: 'Nhân sự',
        jodname: 'IRC HCM',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1734/7ba70b57c1de43f18b8f4056c415dd82.jpg',
        dept: 'irc'
    },
    {
        profileid: '59',
        email: 'baochau.pham@gosu.vn',
        fullname: 'Phạm Bảo Châu',
        jodid: 'Trưởng nhóm',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/59/9478a613bc624cacb659461cea768240.jpg',
        dept: 'hanh chinh nhan su'
    },
    {
        profileid: '90',
        email: 'hong.bui@gosu.vn',
        fullname: 'Bùi Thị Bích Hồng',
        jodid: 'Nhân sự',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/90/ee029fe31e924bbfa0959a218f072fe5.jpg',
        dept: 'hanh chinh nhan su'
    },
    {
        profileid: '140',
        email: 'thu.phung@gosu.vn',
        fullname: 'Phùng Thị Hoài Thu',
        jodid: 'Nhân sự',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/140/b8e8293bc525476fa920b8c7726a772d.jpg',
        dept: 'hanh chinh nhan su'
    },
    {
        profileid: '146',
        email: 'yen.pham@gosu.vn',
        fullname: 'Phạm Thị Yến',
        jodid: 'Nhân sự',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/146/9780cdca63524a4c9cbffce238180377.jpg',
        dept: 'hanh chinh nhan su'
    },
    {
        profileid: '198',
        email: 'diemthu.nguyen@gosu.vn',
        fullname: 'Nguyễn Thị Diễm Thư',
        jodid: 'Nhân sự',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/198/42890650def34a6ca57b4ea59c6d205c.jpg',
        dept: 'hanh chinh nhan su'
    },
    {
        profileid: '3800',
        email: 'van.le@gosu.vn',
        fullname: 'Lê Thị Cẩm Vân',
        jodid: 'Nhân sự',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/3800/ca8b6669fd334246a5055193e779a945.jpg',
        dept: 'hanh chinh nhan su'
    },
    {
        profileid: '3808',
        email: 'tra.luu@gosu.vn',
        fullname: 'Lưu Thị Hương Trà',
        jodid: 'Nhân sự',
        avatar: '/static/uploads/sinhnhat/default_avatar.svg',
        dept: 'hanh chinh nhan su'
    },
    {
        profileid: '3821',
        email: 'thu.le@gosu.vn',
        fullname: 'Lê Minh Thư',
        jodid: 'Nhân sự',
        avatar: '/static/uploads/sinhnhat/default_avatar.svg',
        dept: 'hanh chinh nhan su'
    },
    {
        profileid: '63',
        deptname: 'Ban Giám Đốc',
        shortname: 'DIRECTOR',
        email: 'thach.tran@gosu.vn',
        fullname: 'Trần Quang Thạch',
        jodid: 'Giám Đốc',
        jodname: 'DIRECTOR - GOSU HUE',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/63/61ea9af56eaf4c5e83329edc557f2405.jpg',
        dept: 'gota'
    },
    {
        profileid: '69',
        deptname: 'Trung tâm GOTA',
        shortname: 'GOTA CENTER',
        email: 'huyenvu.le@gosu.vn',
        fullname: 'Lê Huyền Vũ',
        jodid: 'Phó Giám Đốc',
        jodname: 'GOTA DEPUTY DIRECTOR',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/69/dad7a54ee04c46259858c7d0729a6f09.jpg',
        dept: 'gota'
    },
    {
        profileid: '188',
        deptname: 'Truyền Thông',
        shortname: 'Truyền thông',
        email: 'nhan.mai@gosu.vn',
        fullname: 'Mai Thị Thành Nhân',
        jodid: 'Trưởng nhóm',
        jodname: 'MARKETING MANAGER',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/188/e604a40cf52e44e48bd53bbb6799de52.jpg',
        dept: 'gota'
    },
    {
        profileid: '281',
        deptname: 'Trung tâm GOTA',
        shortname: 'GOTA CENTER',
        email: 'tuyen.hoang@gosu.vn',
        fullname: 'Hoàng Tuyến',
        jodid: 'Trưởng nhóm',
        jodname: 'PR - COM DEPUTY MANAGER',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/281/272f5327b5f343d4b7e68528f6488d56.jpg',
        dept: 'gota'
    },
    {
        profileid: '64',
        deptname: 'Vận hành',
        shortname: 'Vận hành',
        email: 'duyvu.le@gosu.vn',
        fullname: 'Lê Duy Vũ',
        jodid: 'Phó nhóm',
        jodname: 'OPERATION CENTER DEPUTY MANAGER',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/64/ca21441419424309b21011ac9a026219.jpg',
        dept: 'gota'
    },
    {
        profileid: '40',
        deptname: 'Vận hành',
        shortname: 'Vận hành',
        email: 'trung.ho@gosu.vn',
        fullname: 'Hồ Hữu Khánh Trung',
        jodid: 'Nhân sự',
        jodname: 'OPERATION',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/40/825d6c73770c478fab24860a8a9966fd.jpg',
        dept: 'gota'
    },
    {
        profileid: '66',
        deptname: 'Vận hành',
        shortname: 'Vận hành',
        email: 'thien.nguyen@gosu.vn',
        fullname: 'Nguyễn Lưu Thiện',
        jodid: 'Nhân sự',
        jodname: 'OPERATION',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/66/ef95f729f7de488580922bb0c1c9bbde.jpg',
        dept: 'gota'
    },
    {
        profileid: '67',
        deptname: 'Vận hành',
        shortname: 'Vận hành',
        email: 'quangdung.tran@gosu.vn',
        fullname: 'Trần Quang Dụng',
        jodid: 'Nhân sự',
        jodname: 'OPERATION',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/67/908df94b254d47d3b905f6009dd2d43a.jpg',
        dept: 'gota'
    },
    {
        profileid: '70',
        deptname: 'Trung tâm GOTA',
        shortname: 'GOTA CENTER',
        email: 'thu.vo@gosu.vn',
        fullname: 'Võ Thị Hà Thu',
        jodid: 'Nhân sự',
        jodname: 'COM',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/70/1eb42e08d26842b0822e09bf00a37e04.jpg',
        dept: 'gota'
    },
    {
        profileid: '71',
        deptname: 'Vận hành',
        shortname: 'Vận hành',
        email: 'kim.le@gosu.vn',
        fullname: 'Lê Minh Hoàng Kim',
        jodid: 'Nhân sự',
        jodname: 'OPERATION',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/71/2dea3a19ddb14ffbb1866ec999595355.jpg',
        dept: 'gota'
    },
    {
        profileid: '132',
        deptname: 'Vận hành',
        shortname: 'Vận hành',
        email: 'tung.tran@gosu.vn',
        fullname: 'Trần Thanh Tùng',
        jodid: 'Nhân sự',
        jodname: 'OPERATION',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/132/478608bd2a3a4daaa6723dd0e3f09988.jpg',
        dept: 'gota'
    },
    {
        profileid: '138',
        deptname: 'Vận hành',
        shortname: 'Vận hành',
        email: 'anhduc.huynh@gosu.vn',
        fullname: 'Huỳnh Anh Đức',
        jodid: 'Nhân sự',
        jodname: 'OPERATION',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/138/891337c9df7540bf9e6d890925b237a4.jpg',
        dept: 'gota'
    },
    {
        profileid: '236',
        deptname: 'Truyền Thông',
        shortname: 'Truyền thông',
        email: 'tuan.phan@gosu.vn',
        fullname: 'Phan Văn Tuấn',
        jodid: 'Nhân sự',
        jodname: 'MARKETING',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/236/ac1d684507164d6dbb08c4dda2a666bd.jpg',
        dept: 'gota'
    },
    {
        profileid: '275',
        deptname: 'Truyền Thông',
        shortname: 'Truyền thông',
        email: 'thanh.huynh@gosu.vn',
        fullname: 'Huỳnh Thanh Thanh',
        jodid: 'Nhân sự',
        jodname: 'COM',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/275/480c006c959647bf89685e75cbe2b2ba.jpg',
        dept: 'gota'
    },
    {
        profileid: '1474',
        deptname: 'Truyền Thông',
        shortname: 'Truyền thông',
        email: 'linh.doan@gosu.vn',
        fullname: 'Đoàn Thị Tuệ Linh',
        jodid: 'Nhân sự',
        jodname: 'COM',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1474/1ef094bbf799465ebbcb10ad743f7943.jpg',
        dept: 'gota'
    },
    {
        profileid: '1493',
        deptname: 'Truyền Thông',
        shortname: 'Truyền thông',
        email: 'le.nguyen@gosu.vn',
        fullname: 'Nguyễn Thị Nhật Lệ',
        jodid: 'Nhân sự',
        jodname: 'COM',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1493/93bd8e5d94ad4cd1a2b9b27127b79057.jpg',
        dept: 'gota'
    },
    {
        profileid: '1504',
        deptname: 'Truyền Thông',
        shortname: 'Truyền thông',
        email: 'nguu.truong@gosu.vn',
        fullname: 'Trương Diên Tâm Ngưu',
        jodid: 'Nhân sự',
        jodname: 'MARKETING',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1504/ab2cbdea52d24a3e9281710a366c0f8a.jpg',
        dept: 'gota'
    },
    {
        profileid: '1658',
        deptname: 'Truyền Thông',
        shortname: 'Truyền thông',
        email: 'quynhnhi.nguyen@gosu.vn',
        fullname: 'Nguyễn Trần Quỳnh Nhi',
        jodid: 'Nhân sự',
        jodname: 'PR - COM',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1658/b17508449dbe42a8bc5a3ac5e600bf59.jpg',
        dept: 'gota'
    },
    {
        profileid: '1660',
        deptname: 'Truyền Thông',
        shortname: 'Truyền thông',
        email: 'thanhhuyen.dang@gosu.vn',
        fullname: 'Đặng Thị Thanh Huyền',
        jodid: 'Nhân sự',
        jodname: 'PR - COM',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1660/cb2f90c6d50041c1805316bfc10664f6.jpg',
        dept: 'gota'
    },
    {
        profileid: '1726',
        deptname: 'Trung tâm GOTA',
        shortname: 'GOTA CENTER',
        email: 'son.nguyen@gosu.vn',
        fullname: 'Nguyễn Văn Sơn',
        jodid: 'Nhân sự',
        jodname: 'COM',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1726/22fd46962275419482e16ce4769606b6.jpg',
        dept: 'gota'
    },
    {
        profileid: '1748',
        deptname: 'Trung tâm GOTA',
        shortname: 'GOTA CENTER',
        email: 'trang.nguyen@gosu.vn',
        fullname: 'Nguyễn Thị Thùy Trang',
        jodid: 'Nhân sự',
        jodname: 'COM',
        area: 'HUI',
        avatar: '/static/uploads/sinhnhat/default_avatar.svg',
        dept: 'gota'
    },
    {
        profileid: '41',
        deptname: 'GAMO',
        shortname: 'GAMO',
        email: 'vanthuong.nguyen@gosu.vn',
        fullname: 'Nguyễn Văn Thương',
        jodid: 'Giám Đốc',
        jodname: 'GAMO DIRECTOR',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/41/b783807def1b4d009739e99c3ba5b278.jpg',
        dept: 'gamo'
    },
    {
        profileid: '244',
        deptname: 'GAMO',
        shortname: 'GAMO',
        email: 'men.phan@gosu.vn',
        fullname: 'Phan Thị Mến',
        jodid: 'Phó Giám Đốc',
        jodname: 'GAMO DEPUTY DIRECTOR',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/244/a895e7929a8d43de9e0440be8a9f8bb6.jpg',
        dept: 'gamo'
    },
    {
        profileid: '189',
        deptname: 'GAMO Marketing',
        shortname: 'GAMO MARKETING',
        email: 'anhthinh.nguyen@gosu.vn',
        fullname: 'Nguyễn Anh Thịnh',
        jodid: 'Trưởng nhóm',
        jodname: 'GAMO MARKETING MANAGER',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/189/e30df325a5f04fa08cc52ce587daa65c.jpg',
        dept: 'gamo'
    },

    {
        profileid: '247',
        deptname: 'GAMO Operation',
        shortname: 'GAMO OPERATION',
        email: 'hung.le@gosu.vn',
        fullname: 'Lê Hoàng Cảnh Hưng',
        jodid: 'Trưởng nhóm',
        jodname: 'GAMO OPERATION MANAGER',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/247/5be4fb8f12a94cf79ceb575d6ab39409.jpg',
        dept: 'gamo'
    },
    {
        profileid: '39',
        deptname: 'GAMO Operation',
        shortname: 'GAMO OPERATION',
        email: 'hung.truong@gosu.vn',
        fullname: 'Trương Sỷ Hưng',
        jodid: 'Nhân sự',
        jodname: 'GAMO OPERATION',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/39/0515d0252fe749fdbaa06e98c38b94ee.jpg',
        dept: 'gamo'
    },
    {
        profileid: '104',
        deptname: 'GAMO Community',
        shortname: 'GAMO COMMUNITY',
        email: 'thuynhung.le@gosu.vn',
        fullname: 'Lê Thị Thùy Nhung',
        jodid: 'Nhân sự',
        jodname: 'GAMO COMMUNITY ',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/104/a753c6752532430d892c9a387ab21113.jpg',
        dept: 'gamo'
    },
    {
        profileid: '1296',
        deptname: 'GAMO Operation',
        shortname: 'GAMO OPERATION',
        email: 'haitrung.tran@gosu.vn',
        fullname: 'Trần Hải Trung',
        jodid: 'Nhân sự',
        jodname: 'GAMO OPERATION',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1296/3d88f9c9a90a4aa79ffd7369c6bac842.jpg',
        dept: 'gamo'
    },
    {
        profileid: '1297',
        deptname: 'GAMO Community',
        shortname: 'GAMO COMMUNITY',
        email: 'thanh.tran@gosu.vn',
        fullname: 'Trần Thị Phương Thanh',
        jodid: 'Nhân sự',
        jodname: 'GAMO COMMUNITY ',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1297/6b9f256a60df481f8c9b35f90db2cc9e.jpg',
        dept: 'gamo'
    },
    {
        profileid: '1408',
        deptname: 'GAMO Community',
        shortname: 'GAMO COMMUNITY',
        email: 'xuanthanh.nguyen@gosu.vn',
        fullname: 'Nguyễn Ngọc Xuân Thành',
        jodid: 'Nhân sự',
        jodname: 'GAMO COMMUNITY ',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1408/3426e9d137964eb6815b9f8e5e4c47c4.jpg',
        dept: 'gamo'
    },
    {
        profileid: '1549',
        deptname: 'GAMO Operation',
        shortname: 'GAMO OPERATION',
        email: 'phuoc.truong@gosu.vn',
        fullname: 'Trương Quang Phước',
        jodid: 'Nhân sự',
        jodname: 'GAMO OPERATION',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1549/e70b222fd15e43738f29a094b370a1bd.jpg',
        dept: 'gamo'
    },
    {
        profileid: '1560',
        deptname: 'GAMO Marketing',
        shortname: 'GAMO MARKETING',
        email: 'vietminh.le@gosu.vn',
        fullname: 'Lê Viết Minh',
        jodid: 'Nhân sự',
        jodname: 'GAMO MARKETING',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1560/d2261d0045d349e8bf1f19947df7da82.jpg',
        dept: 'gamo'
    },
    {
        profileid: '1579',
        deptname: 'GAMO Operation',
        shortname: 'GAMO OPERATION',
        email: 'khanhlinh.tran@gosu.vn',
        fullname: 'Trần Khánh Linh',
        jodid: 'Nhân sự',
        jodname: 'GAMO OPERATION',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1579/b52f61908a524bd9bea9f1c47562a965.jpg',
        dept: 'gamo'
    },
    {
        profileid: '1719',
        deptname: 'GAMO Marketing',
        shortname: 'GAMO MARKETING',
        email: 'hieu.ho@gosu.vn',
        fullname: 'Hồ Đăng Hiếu',
        jodid: 'Nhân sự',
        jodname: 'GAMO COMMUNITY ',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1719/96b69096f48c4df2b97ae908334f0488.jpg',
        dept: 'gamo'
    },
    {
        profileid: '3787',
        deptname: 'GAMO Marketing',
        shortname: 'GAMO MARKETING',
        email: 'binh.phan@gosu.vn',
        fullname: 'Phan Duy Bình',
        jodid: 'Nhân sự',
        jodname: 'GAMO MARKETING',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/3787/c763d5d612ca4f77997d1cd323b1e893.jpg',
        dept: 'gamo'
    },
    {
        profileid: '3791',
        deptname: 'GAMO Design',
        shortname: 'GAMO Design',
        email: 'trongduc.vo@gosu.vn',
        fullname: 'Võ Trọng Đức',
        jodid: 'Nhân sự',
        jodname: 'GAMO DESIGNER',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/3791/f89751223c61489795c508f06fdf92e8.jpg',
        dept: 'gamo'
    },
    {
        profileid: '123',
        deptname: 'Thiết kế',
        shortname: 'GRAPHIC DESIGN ',
        email: 'xuanbinh.dang@gosu.vn',
        fullname: 'Đặng Xuân Bình',
        jodid: 'Trưởng nhóm',
        jodname: 'GRAPHIC DESIGN HUE - MANAGER',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/123/3ab2931b92a0488c9386214356954d62.jpg',
        dept: 'design'
    },

    {
        profileid: '167',
        deptname: 'Thiết Kế',
        shortname: 'GRAPHIC DESIGN ',
        email: 'giau.nguyen@gosu.vn',
        fullname: 'Nguyễn Thị Ngọc Giàu',
        jodid: 'Trưởng nhóm',
        jodname: 'GRAPHIC DESIGN HCM - MANAGER',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/167/74603372c71b4548b43b1d7e11222b0a.jpg',
        dept: 'design'
    },
    {
        profileid: '105',
        deptname: 'Thiết kế',
        shortname: 'GRAPHIC DESIGN ',
        email: 'long.pham@gosu.vn',
        fullname: 'Phạm Huỳnh Thanh Long',
        jodid: 'Nhân sự',
        jodname: 'GRAPHIC DESIGN HUE',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/105/3db3a779fab247c393aeb3836c0e7f19.jpg',
        dept: 'design'
    },
    {
        profileid: '124',
        deptname: 'Thiết kế',
        shortname: 'GRAPHIC DESIGN ',
        email: 'chuong.dinh@gosu.vn',
        fullname: 'Đinh Khắc Thiên Chương',
        jodid: 'Nhân sự',
        jodname: 'GRAPHIC DESIGN HUE',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/124/8543144c77374f989566889873af2e2e.jpg',
        dept: 'design'
    },
    {
        profileid: '125',
        deptname: 'Thiết kế',
        shortname: 'GRAPHIC DESIGN ',
        email: 'thong.hoang@gosu.vn',
        fullname: 'Hoàng Thông',
        jodid: 'Nhân sự',
        jodname: 'GRAPHIC DESIGN HUE',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/125/139254e6db3844158f88c8622c7347bb.jpg',
        dept: 'design'
    },
    {
        profileid: '127',
        deptname: 'Thiết kế',
        shortname: 'GRAPHIC DESIGN ',
        email: 'nam.thai@gosu.vn',
        fullname: 'Thái Thành Nam',
        jodid: 'Nhân sự',
        jodname: 'GRAPHIC DESIGN HUE',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/127/6c816aeaca704fbf903be1202154a040.jpg',
        dept: 'design'
    },
    {
        profileid: '163',
        deptname: 'Thiết Kế',
        shortname: 'GRAPHIC DESIGN ',
        email: 'triet.do@gosu.vn',
        fullname: 'Đỗ Xuân Minh Triết',
        jodid: 'Nhân sự',
        jodname: 'GRAPHIC DESIGN HCM',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/163/6d8b5deb58484c7c83989ae7d2d9b43c.jpg',
        dept: 'design'
    },
    {
        profileid: '164',
        deptname: 'Thiết Kế',
        shortname: 'GRAPHIC DESIGN ',
        email: 'quynh.le@gosu.vn',
        fullname: 'Lê Ái Quỳnh',
        jodid: 'Nhân sự',
        jodname: 'GRAPHIC DESIGN HCM',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/164/a57427c2fd1042fdb791e9c22bdea66e.jpg',
        dept: 'design'
    },
    {
        profileid: '166',
        deptname: 'Thiết Kế',
        shortname: 'GRAPHIC DESIGN ',
        email: 'uyen.pham@gosu.vn',
        fullname: 'Phạm Ngọc Tú Uyên',
        jodid: 'Nhân sự',
        jodname: 'GRAPHIC DESIGN HCM',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/166/fb2e8ccdf7c24d57992e930e03abfc2c.jpg',
        dept: 'design'
    },
    {
        profileid: '1354',
        deptname: 'Thiết kế',
        shortname: 'GRAPHIC DESIGN ',
        email: 'thanh.nguyen@gosu.vn',
        fullname: 'Nguyễn Phước Thanh',
        jodid: 'Nhân sự',
        jodname: 'GRAPHIC DESIGN HUE',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1354/91a77eb78a1f4cb7970c069454813da2.jpg',
        dept: 'design'
    },
    {
        profileid: '1412',
        deptname: 'Thiết Kế',
        shortname: 'GRAPHIC DESIGN ',
        email: 'anh.vo@gosu.vn',
        fullname: 'Võ Hoàng Tú Anh',
        jodid: 'Nhân sự',
        jodname: 'GRAPHIC DESIGN HCM',
        area: 'SGN',
        avatar: '/static/uploads/sinhnhat/default_avatar.svg',
        dept: 'design'
    },
    {
        profileid: '1416',
        deptname: 'Thiết Kế',
        shortname: 'GRAPHIC DESIGN ',
        email: 'anh.tran@gosu.vn',
        fullname: 'Trần Mai Anh',
        jodid: 'Nhân sự',
        jodname: 'GRAPHIC DESIGN HCM',
        area: 'SGN',
        avatar: '/static/uploads/sinhnhat/default_avatar.svg',
        dept: 'design'
    },
    {
        profileid: '1604',
        deptname: 'Thiết kế',
        shortname: 'GRAPHIC DESIGN ',
        email: 'uyen.le@gosu.vn',
        fullname: 'Lê Nguyễn Hoài Uyên',
        jodid: 'Nhân sự',
        jodname: 'GRAPHIC DESIGN HUE',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1604/d1d4946b35ce47369497cd5d7811d0c6.jpg',
        dept: 'design'
    },
    {
        profileid: '1605',
        deptname: 'Thiết kế',
        shortname: 'GRAPHIC DESIGN ',
        email: 'cuong.vo@gosu.vn',
        fullname: 'Võ Trọng Minh Cương',
        jodid: 'Nhân sự',
        jodname: 'GRAPHIC DESIGN HUE',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1605/0a7fbaa110ee480db17eef39a0b93335.jpg',
        dept: 'design'
    },
    {
        profileid: '1597',
        deptname: 'Trung tâm Công Nghệ Thông Tin',
        shortname: 'ITC',
        email: 'duc.nguyen@gosu.vn',
        fullname: 'Nguyễn Hồ Minh Đức',
        jodid: 'Giám Đốc',
        jodname: 'ITC DIRECTOR',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1597/34f560b78d9c413d9fa100ab596e9491.jpg',
        dept: 'itc'
    },
    {
        profileid: '116',
        deptname: 'Trung tâm Công Nghệ Thông Tin',
        shortname: 'ITC',
        email: 'nhi.tran@gosu.vn',
        fullname: 'Trần Lê Phương Nhi',
        jodid: 'Trưởng nhóm',
        jodname: 'ID&PAYMENT MANAGER',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/116/9f3f88dcda6c4c028677926f75f12f27.jpg',
        dept: 'itc'
    },
    {
        profileid: '109',
        deptname: 'Kỹ thuật Phần mềm',
        shortname: 'SOFTWARE TECHNOLOGY',
        email: 'congminh.le@gosu.vn',
        fullname: 'Lê Công Minh',
        jodid: 'Trưởng nhóm',
        jodname: 'SOFTWARE TECHNOLOGY MANAGER',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/109/4f242fc9db094c71890ef1bb0968eaf5.jpg',
        dept: 'itc'
    },
    {
        profileid: '1380',
        deptname: 'Trung tâm Công Nghệ Thông Tin',
        shortname: 'ITC',
        email: 'kha.le@gosu.vn',
        fullname: 'Lê Duy Kha',
        jodid: 'Nhân sự',
        jodname: 'ID & PAYMENT HCM',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1380/92d2adabbe634022b46bbd433ea5e070.jpg',
        dept: 'itc'
    },
    {
        profileid: '1598',
        deptname: 'Trung tâm Công Nghệ Thông Tin',
        shortname: 'ITC',
        email: 'tong.ho@gosu.vn',
        fullname: 'Hồ Thế Tông',
        jodid: 'Nhân sự',
        jodname: 'R&D MANAGER',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1598/6c1098693164421fafdf06e86ff0a359.jpg',
        dept: 'itc'
    },
    {
        profileid: '1600',
        deptname: 'Trung tâm Công Nghệ Thông Tin',
        shortname: 'ITC',
        email: 'tien.huynh@gosu.vn',
        fullname: 'Huỳnh Đình Tiến',
        jodid: 'Nhân sự',
        jodname: 'RESEARCH & DEVELOPMENT',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1600/6247c4df61bb416ba41471cc433dc508.jpg',
        dept: 'itc'
    },
    {
        profileid: '1731',
        deptname: 'Trung tâm Công Nghệ Thông Tin',
        shortname: 'ITC',
        email: 'vuhung.nguyen@gosu.vn',
        fullname: 'Nguyễn Vũ Hùng',
        jodid: 'Nhân sự',
        jodname: 'RESEARCH & DEVELOPMENT',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1731/6dd81c23f6204746b87a61ed393e67ac.jpg',
        dept: 'itc'
    },
    {
        profileid: '2764',
        deptname: 'Trung tâm Công Nghệ Thông Tin',
        shortname: 'ITC',
        email: 'toan.dinh@gosu.vn',
        fullname: 'Đinh Công Toàn',
        jodid: 'Nhân sự',
        jodname: 'RESEARCH & DEVELOPMENT',
        area: 'SGN',
        avatar: '/static/uploads/sinhnhat/default_avatar.svg',
        dept: 'itc'
    },
    {
        profileid: '3786',
        deptname: 'Trung tâm Công Nghệ Thông Tin',
        shortname: 'ITC',
        email: 'loc.tran@gosu.vn',
        fullname: 'Trần Vũ Lộc',
        jodid: 'Nhân sự',
        jodname: 'RESEARCH & DEVELOPMENT',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/3786/d67ddb58bb184070936167b0e09c3a09.jpg',
        dept: 'itc'
    },
    {
        profileid: '3810',
        deptname: 'Tài khoản & Thanh toán',
        shortname: 'ID & PAYMENT',
        email: 'minhhuy.nguyen@gosu.vn',
        fullname: 'Nguyễn Minh Huy',
        jodid: 'Nhân sự',
        jodname: 'ID & PAYMENT HCM',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/3810/2dfa685be762403ea03096285dcdb9d3.jpg',
        dept: 'itc'
    },
    {
        profileid: '112',
        deptname: 'Kỹ thuật Phần mềm',
        shortname: 'SOFTWARE TECHNOLOGY',
        email: 'luan.nguyen@gosu.vn',
        fullname: 'Nguyễn Hữu Luân',
        jodid: 'Nhân sự',
        jodname: 'SOFTWARE TECHNOLOGY',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/112/abc589d159a54e65be8b4e86879a7a75.jpg',
        dept: 'itc'
    },
    {
        profileid: '113',
        deptname: 'Kỹ thuật Phần mềm',
        shortname: 'SOFTWARE TECHNOLOGY',
        email: 'lan.nguyen@gosu.vn',
        fullname: 'Nguyễn Ngọc Lân',
        jodid: 'Nhân sự',
        jodname: 'SOFTWARE TECHNOLOGY',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/113/ea1ccc20941f412ba4ad585de9ebad3c.jpg',
        dept: 'itc'
    },
    {
        profileid: '114',
        deptname: 'Kỹ thuật Phần mềm',
        shortname: 'SOFTWARE TECHNOLOGY',
        email: 'huynh.nguyen@gosu.vn',
        fullname: 'Nguyễn Lương Huynh',
        jodid: 'Nhân sự',
        jodname: 'SOFTWARE TECHNOLOGY',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/114/b211536bd1e14792a7dcebfd9a423d48.jpg',
        dept: 'itc'
    },
    {
        profileid: '226',
        deptname: 'Kỹ thuật Phần mềm',
        shortname: 'SOFTWARE TECHNOLOGY',
        email: 'congcuong.nguyen@gosu.vn',
        fullname: 'Nguyễn Công Cường',
        jodid: 'Nhân sự',
        jodname: 'SOFTWARE TECHNOLOGY',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/226/fc7f26a9119b4c8c90125d92ce48f271.jpg',
        dept: 'itc'
    },
    {
        profileid: '1706',
        deptname: 'Kỹ thuật Phần mềm',
        shortname: 'SOFTWARE TECHNOLOGY',
        email: 'son.truong@gosu.vn',
        fullname: 'Trương Sỷ Hồng Sơn',
        jodid: 'Nhân sự',
        jodname: 'SOFTWARE TECHNOLOGY',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1706/cfb2c1e5a1d848a9915a78d46c92b6ff.jpg',
        dept: 'itc'
    },
    {
        profileid: '1710',
        deptname: 'Kỹ thuật Phần mềm',
        shortname: 'SOFTWARE TECHNOLOGY',
        email: 'nghin.cao@gosu.vn',
        fullname: 'Cao Thọ Hai Nghìn',
        jodid: 'Nhân sự',
        jodname: 'SOFTWARE TECHNOLOGY',
        area: 'HUI',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1710/6ba25bc795c24d1cb14a2078049cc00b.jpg',
        dept: 'itc'
    },
    {
        profileid: '183',
        deptname: 'CTCP Trực tuyến GOSU',
        shortname: 'GOSU HN',
        email: 'kien.tran@gosu.vn',
        fullname: 'Trần Trọng Kiên',
        jodid: 'Giám Đốc',
        jodname: 'DIRECTOR - GOSU HN',
        area: 'HAN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/183/f297f393cbcd4a24a77d4a360aaf5080.jpg',
        dept: 'gbc'
    },
    {
        profileid: '227',
        deptname: 'CTCP Trực tuyến GOSU',
        shortname: 'GOSU HN',
        email: 'cuong.le@gosu.vn',
        fullname: 'Lê Hải Cường',
        jodid: 'Nhân sự',
        jodname: 'COM',
        area: 'HAN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/227/c3b21e69b6314c3cad9e4af190380cc8.jpg',
        dept: 'gbc'
    },
    {
        profileid: '1310',
        deptname: 'CTCP Trực tuyến GOSU',
        shortname: 'GOSU HN',
        email: 'nam.dam@gosu.vn',
        fullname: 'Đàm Đình Nam',
        jodid: 'Nhân sự',
        jodname: 'GLOBAL BUSINESS',
        area: 'HAN',
        avatar: '/static/uploads/sinhnhat/default_avatar.svg',
        dept: 'gbc'
    },
    {
        profileid: '1633',
        deptname: 'CTCP Trực tuyến GOSU',
        shortname: 'GOSU HN',
        email: 'chidung.nguyen@gosu.vn',
        fullname: 'Nguyễn Chí Dũng',
        jodid: 'Nhân sự',
        jodname: 'COM',
        area: 'HAN',
        avatar: '/static/uploads/sinhnhat/default_avatar.svg',
        dept: 'gbc'
    },
    {
        profileid: '1635',
        deptname: 'CTCP Trực tuyến GOSU',
        shortname: 'GOSU HN',
        email: 'nam.dao@gosu.vn',
        fullname: 'Đào Hải Nam',
        jodid: 'Nhân sự',
        jodname: 'COM',
        area: 'HAN',
        avatar: '/static/uploads/sinhnhat/default_avatar.svg',
        dept: 'gbc'
    },
    {
        profileid: '2777',
        deptname: 'CTCP Trực tuyến GOSU',
        shortname: 'GOSU HN',
        email: 'quocviet.nguyen@gosu.vn',
        fullname: 'Nguyễn Quốc Việt',
        jodid: 'Nhân sự',
        jodname: 'GLOBAL BUSINESS',
        area: 'HAN',
        avatar: '/static/uploads/sinhnhat/default_avatar.svg',
        dept: 'gbc'
    },
    {
        profileid: '175',
        deptname: 'Trung tâm CMC',
        shortname: 'CMC CENTER ',
        email: 'tuanthanh.nguyen@gosu.vn',
        fullname: 'Nguyễn Tuấn Thanh',
        jodid: 'Giám Đốc',
        jodname: 'CMC DIRECTOR',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/175/7656bd303a2840069fbfbe804a1db101.jpg',
        dept: 'cmc'
    },
    {
        profileid: '177',
        deptname: 'Trung tâm CMC',
        shortname: 'CMC CENTER ',
        email: 'truong.pham@gosu.vn',
        fullname: 'Phạm Xuân Trường',
        jodid: 'Trưởng nhóm',
        jodname: 'MARKETING MANAGER',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/177/24fac3bb43d34fcab23e1318e49b9207.jpg',
        dept: 'cmc'
    },

    {
        profileid: '232',
        deptname: 'Trung tâm CMC',
        shortname: 'CMC CENTER ',
        email: 'hoang.nguyen@gosu.vn',
        fullname: 'Nguyễn Đức Hoàng',
        jodid: 'Trưởng nhóm',
        jodname: 'OPERATION MANAGER',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/232/39f2f1d94a5e4feab61f8f916214efa9.jpg',
        dept: 'cmc'
    },
    {
        profileid: '173',
        deptname: 'Trung tâm CMC',
        shortname: 'CMC CENTER ',
        email: 'thanhlong.nguyen@gosu.vn',
        fullname: 'Nguyễn Thành Long',
        jodid: 'Trưởng nhóm',
        jodname: 'CREATIVE MANAGER',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/173/4b70aa45ca214b42a77dee607e454bdd.jpg',
        dept: 'cmc'
    },
    {
        profileid: '170',
        deptname: 'Vận hành dịch vụ',
        shortname: 'OPERATION',
        email: 'kiet.duong@gosu.vn',
        fullname: 'Dương Chí Kiệt',
        jodid: 'Nhân sự',
        jodname: 'OPERATION',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/170/75135f9771c240dab6b548697390cf44.jpg',
        dept: 'cmc'
    },
    {
        profileid: '172',
        deptname: 'Vận hành dịch vụ',
        shortname: 'OPERATION',
        email: 'huutrong.nguyen@gosu.vn',
        fullname: 'Nguyễn Hữu Trọng',
        jodid: 'Nhân sự',
        jodname: 'OPERATION',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/172/358c137e7ada4a60bd6f6d0dff593ed4.jpg',
        dept: 'cmc'
    },
    {
        profileid: '1364',
        deptname: 'Tiếp thị kỹ thuật số',
        shortname: 'DIGITAL MARKETING',
        email: 'thiphuong.le@gosu.vn',
        fullname: 'Lê Thị Phương',
        jodid: 'Nhân sự',
        jodname: 'MARKETING',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1364/acd90e74400d4c94b80eb2d25bcffb2e.jpg',
        dept: 'cmc'
    },
    {
        profileid: '1366',
        deptname: 'Quản lý Cộng đồng',
        shortname: 'COMMUNITY',
        email: 'tran.ong@gosu.vn',
        fullname: 'Ông Liễu Trân',
        jodid: 'Nhân sự',
        jodname: 'COMMUNITY',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1366/bc796a3a1cba4fffaabe9e30453f663f.jpg',
        dept: 'cmc'
    },
    {
        profileid: '1480',
        deptname: 'Quản lý Cộng đồng',
        shortname: 'COMMUNITY',
        email: 'huyenanh.vu@gosu.vn',
        fullname: 'Vũ Huyền Anh',
        jodid: 'Nhân sự',
        jodname: 'COMMUNITY',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1480/a0c72a0617a44715b8f0c36d69aa7031.jpg',
        dept: 'cmc'
    },
    {
        profileid: '1641',
        deptname: 'Vận hành dịch vụ',
        shortname: 'OPERATION',
        email: 'kien.mai@gosu.vn',
        fullname: 'Mai Trung Kiên',
        jodid: 'Nhân sự',
        jodname: 'OPERATION',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/1641/41d638edd09342d28e487481549020f6.jpg',
        dept: 'cmc'
    },
    {
        profileid: '1705',
        deptname: 'Quản lý Cộng đồng',
        shortname: 'COMMUNITY',
        email: '1_duc.vo@gosu.vn',
        fullname: 'Võ Huỳnh Đức',
        jodid: 'Nhân sự',
        jodname: 'COM COLLABORATOR',
        area: 'SGN',
        avatar: '/static/uploads/sinhnhat/default_avatar.svg',
        dept: 'cmc'
    },
    {
        profileid: '2753',
        deptname: 'Xây dựng ý tưởng',
        shortname: 'CONTENT CREATOR',
        email: 'hoang.vo@gosu.vn',
        fullname: 'Võ Huy Hoàng',
        jodid: 'Nhân sự',
        jodname: 'CREATIVE',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/2753/6e382f14ce7643b3b1d95ccfbf823d21.jpg',
        dept: 'cmc'
    },
    {
        profileid: '2754',
        deptname: 'Xây dựng ý tưởng',
        shortname: 'CONTENT CREATOR',
        email: 'congthanh.nguyen@gosu.vn',
        fullname: 'Nguyễn Công Thành',
        jodid: 'Nhân sự',
        jodname: 'CREATIVE',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/2754/f2866de89ac4495599cafd8772898cbd.jpg',
        dept: 'cmc'
    },
    {
        profileid: '3798',
        deptname: 'Quản lý Cộng đồng',
        shortname: 'COMMUNITY',
        email: null,
        fullname: 'Vũ Minh Tiến',
        jodid: 'Nhân sự',
        jodname: 'COM COLLABORATOR',
        area: 'SGN',
        avatar: '/static/uploads/sinhnhat/default_avatar.svg',
        dept: 'cmc'
    },
    {
        profileid: '3807',
        deptname: 'Vận hành dịch vụ',
        shortname: 'OPERATION',
        email: 'ngan.nguyen@gosu.vn',
        fullname: 'Nguyễn Thu Ngân',
        jodid: 'Nhân sự',
        jodname: 'OPERATION',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/3807/50bf675d2e844ba7979f1819b15dc8e0.jpg',
        dept: 'cmc'
    },
    {
        profileid: '3809',
        deptname: 'Quản lý Cộng đồng',
        shortname: 'COMMUNITY',
        email: 'lai.le@gosu.vn',
        fullname: 'Lê Thị Ngọc Lài',
        jodid: 'Nhân sự',
        jodname: 'COMMUNITY',
        area: 'SGN',
        avatar: '/static/uploads/sinhnhat/default_avatar.svg',
        dept: 'cmc'
    },
    {
        profileid: '3811',
        deptname: 'Tiếp thị kỹ thuật số',
        shortname: 'DIGITAL MARKETING',
        email: 'behien.le@gosu.vn',
        fullname: 'Lê Thị Bé Hiền',
        jodid: 'Nhân sự',
        jodname: 'MARKETING',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/3811/1cf3cb167daa427ea0c790a38a99ea19.jpg',
        dept: 'cmc'
    },
    {
        profileid: '3814',
        deptname: 'Vận hành dịch vụ',
        shortname: 'OPERATION',
        email: 'ngochieu.pham@gosu.vn',
        fullname: 'Phạm Huỳnh Ngọc Hiếu',
        jodid: 'Nhân sự',
        jodname: 'OPERATION',
        area: 'SGN',
        avatar: 'https://static.gosucorp.vn/hrm/avatar/3814/4ba0a690825a4fdaa7db6a2bf0b59541.jpg',
        dept: 'cmc'
    },
    {
        profileid: '3823',
        deptname: 'Tiếp thị kỹ thuật số',
        shortname: 'DIGITAL MARKETING',
        email: 'linh.to@gosu.vn',
        fullname: 'Tô Bảo Linh',
        jodid: 'Nhân sự',
        jodname: 'MARKETING',
        area: 'SGN',
        avatar: '/static/uploads/sinhnhat/default_avatar.svg',
        dept: 'cmc'
    }
];

export { Employee };
